// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YellowBook.API.Data;

#nullable disable

namespace YellowBook.API.Migrations
{
    [DbContext(typeof(YellowBookDbContext))]
    [Migration("20260515222941_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YellowBook.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YellowBook.API.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Main Street, Downtown",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxury hotel with conference facilities.",
                            Email = "info@grandplaza.com",
                            Name = "Grand Plaza Hotel",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Address = "250 Health Avenue",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 2, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Full-service medical clinic.",
                            Email = "contact@sunrisemed.com",
                            Name = "Sunrise Medical Center",
                            Phone = "+1-555-0202"
                        },
                        new
                        {
                            Id = 3,
                            Address = "42 Culinary Lane",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 3, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fine dining and catering.",
                            Email = "hello@goldenfork.com",
                            Name = "Golden Fork Restaurant",
                            Phone = "+1-555-0303"
                        });
                });

            modelBuilder.Entity("YellowBook.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hotels"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Retail"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Services"
                        });
                });

            modelBuilder.Entity("YellowBook.API.Models.Business", b =>
                {
                    b.HasOne("YellowBook.API.Models.Category", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YellowBook.API.Models.Category", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
